apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twang77-deploy
  name: twang77-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: twang77-deploy
  template:
    metadata:
      labels:
        app: twang77-deploy
    spec:
      containers:
      - image: cloudsihmar/takin:latest
        name: pet
